global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3001']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:3002']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3003']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3004']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3005']
